version: "3.8"

services:
  meilisearch:
    image: "getmeili/meilisearch:v1.3.5"
    ports:
      - "7700:7700"
    environment:
      - "MEILISEARCH_MASTER_KEY='amogus'"
    volumes:
      - ./tmp/meilisearch:/meili_data
  redis:
    image: "redis"
    container_name: "e45g_redis"
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./tmp/redis:/data

